// Generated by `npm run build-resume` from src/content/resume.md.
// Do not edit.

type ExperienceItem = {
  company: string;
  role: string;
  date: string;
  highlights: string[];
};

export const experience: ExperienceItem[] = [
  {
    "company": "Lockerbie Technology (Musaeum Ltd, UK group)",
    "role": "Full-Stack Engineer — Internal Platform",
    "date": "Taipei, Taiwan · Dec 2024 – Jul 2026",
    "highlights": [
      "Built and ran an early-stage internal project-management platform for the **UK construction sector**, working to **ISO 19650** information-management principles. One of two engineers, sole author of the **Next.js / TypeScript** frontend and its **UI patterns**.",
      "Refactored the backend into the team's **event-driven modular monolith**, with modules communicating over **RabbitMQ** instead of importing each other, and set up the module template the team builds against. The direction was the team's; the refactor was mine, with **RabbitMQ** and **ArangoDB** new to me.",
      "Diagnosed a **RabbitMQ** RPC bug where a stale, uninitialised consumer round-robined into login lookups and failed every user's first attempt; fixed it with a fail-fast DB check before broker registration.",
      "Packaged deploys into a three-file runner folder — **Docker Compose**, Makefile, env — that pulls the promoted production image from **GHCR**: no source checkout, no dev dependencies, an ~80 MB download instead of a full build.",
      "Given a requirement that layers stay independent, chose **Next.js App Router** and introduced a **BFF security boundary** with server-managed authentication and centralised **CSRF** protection, keeping backend credentials out of browser JavaScript.",
      "Designed the platform's authorisation model — organisation-level and project-scoped roles resolved into capability flags, so services never reimplement access logic. Tested with **Vitest**, **React Testing Library** and **pytest**."
    ]
  },
  {
    "company": "SPIN.FASHION by Lablaco",
    "role": "Full Stack Engineer & Founding Partner",
    "date": "Singapore · Remote · Aug 2024 – Oct 2024",
    "highlights": [
      "Founding partner on the in-store desktop app. Cleared the **macOS code-signing, notarisation and auto-update** work blocking release, shipped the **Electron** app, and wrote the deployment steps down for the team."
    ]
  },
  {
    "company": "Find Recruiter",
    "role": "Software Engineer",
    "date": "Taipei, Taiwan · Aug 2022 – May 2024",
    "highlights": [
      "Took over frontend delivery on a **B2B and B2C recruitment and ATS platform** in **React and TypeScript** — two-engineer product team, reporting to the CTO — as the work was handed to me across the two years. Migrated features to **TypeScript** as part of an incremental codebase-wide migration, and authored around 100 of its shared components.",
      "Wrote the **Server-Sent Events** channel the frontend consumed AI-generated drafts through.",
      "Built job-opening filtering on the careers pages end to end — filter bar, sorting, the employer settings behind it, and a shared dropdown component with tests."
    ]
  },
  {
    "company": "Independent / Freelance Engineering",
    "role": "Product Engineer",
    "date": "Remote · 2020 – 2024",
    "highlights": [
      "Built the **Next.js frontend for a Bitcoin coin-selection research tool** with a **BDK core maintainer** (2023), and fixed and optimised a **BigCommerce** storefront for Bdigital (2024)."
    ]
  }
];
