import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { projectsConfig } from "../src/content/projects.config.js";
import { experiencePortfolio } from "../src/content/portfolio.config.js";

const ROOT = process.cwd();
const RESUME_PATH = path.join(ROOT, "src", "content", "resume.md");
const OUTPUT_DIR = path.join(ROOT, "output");
const BUILD_MD = path.join(OUTPUT_DIR, "resume.build.md");
const RESUME_DATA_PATH = path.join(ROOT, "src/lib/resumeData.ts");

/*
--------------------------------------------------
Helpers
--------------------------------------------------
*/

function ensureDirectories() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR);
  }
}

function readResume() {
  return fs.readFileSync(RESUME_PATH, "utf-8");
}

/*
--------------------------------------------------
Projects come from projects.config.ts, so a fact lives in one place and is
rendered twice: a card on the site, one line on the PDF. A project with no
resumeLine is site-only — the page has room, one page of A4 does not.
--------------------------------------------------
*/

const PROJECTS_MARKER =
  "<!-- generated from src/content/projects.config.ts — projects with a resumeLine -->";

function withProjects(markdown) {
  const lines = projectsConfig
    .filter((p) => p.resumeLine)
    .map((p) => `**${p.name}** — _Founder / Product Engineer_ · ${p.resumeLine}`)
    .join("\n\n");

  if (!markdown.includes(PROJECTS_MARKER)) {
    throw new Error("resume.md is missing the projects marker comment");
  }

  return markdown.replace(PROJECTS_MARKER, lines);
}

/*
--------------------------------------------------
Markdown Section Parser
--------------------------------------------------
*/

function extractSection(title, markdown) {
  const lines = markdown.split("\n");
  const normalizedTitle = title.trim().toLowerCase();

  let collecting = false;
  let startHeadingLevel = 0;
  const result = [];

  for (const line of lines) {
    const headingMatch = line.trim().match(/^(#{1,6})\s+(.+)$/);

    if (!collecting) {
      if (
        headingMatch &&
        headingMatch[2].trim().toLowerCase() === normalizedTitle
      ) {
        collecting = true;
        startHeadingLevel = headingMatch[1].length;
      }
      continue;
    }

    if (headingMatch && headingMatch[1].length <= startHeadingLevel) {
      break;
    }

    result.push(line);
  }

  return result.join("\n").trim();
}
/*
--------------------------------------------------
Experience Parser
--------------------------------------------------
*/

function parseExperience(section) {
  const entries = [];

  const blocks = section.split("## ").filter(Boolean);

  blocks.forEach((block) => {
    const lines = block
      .trim()
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    const company = lines[0].trim();
    let roleLine = lines[1] || "";
    let dateLine =
      lines.find(
        (line, index) =>
          index > 1 && !line.startsWith("- ") && !line.startsWith("#")
      ) || "";

    // The résumé keeps role, location and dates on one line to save vertical
    // space on the printed page. Split them back apart so the site still gets
    // separate role and date fields.
    if (!dateLine && roleLine.includes(" · ")) {
      const cut = roleLine.indexOf(" · ");
      dateLine = roleLine.slice(cut + 3).trim();
      roleLine = roleLine.slice(0, cut).trim();
    }

    const highlights = lines
      .filter((l) => l.startsWith("- "))
      .map((l) => l.replace("- ", "").trim());

    entries.push({
      company,
      role: roleLine,
      date: dateLine,
      highlights,
    });
  });

  return entries;
}

/*
--------------------------------------------------
Build Resume Data
--------------------------------------------------
*/

function buildResumeData(markdown) {
  const summary = extractSection("Summary", markdown);

  const experience = parseExperience(extractSection("Experience", markdown));

  // Only what the site actually imports. Skills come from
  // portfolio.config.ts and projects from projects.config.ts; generating
  // them here too produced exports nobody read, and made editing skills in
  // resume.md look broken — the PDF changed, the site did not.
  // The site joins portfolio copy to experience by company name, and a
  // mismatch renders an empty card with no error. Fail here instead.
  const companies = experience.map((e) => e.company);
  const orphans = Object.keys(experiencePortfolio).filter(
    (key) => !companies.includes(key)
  );
  if (orphans.length) {
    throw new Error(
      `portfolio.config.ts has copy for ${orphans
        .map((o) => `"${o}"`)
        .join(", ")}, which no longer matches any company in resume.md. ` +
        `Companies are: ${companies.map((c) => `"${c}"`).join(", ")}`
    );
  }

  const content = `// Generated by \`npm run build-resume\` from src/content/resume.md.
// Do not edit.

type ExperienceItem = {
  company: string;
  role: string;
  date: string;
  highlights: string[];
};

export const summary = ${JSON.stringify(summary, null, 2)};

export const experience: ExperienceItem[] = ${JSON.stringify(
    experience,
    null,
    2
  )};
`;

  fs.writeFileSync(RESUME_DATA_PATH, content);

  console.log("✅ Updated src/lib/resumeData.ts");
}

/*
--------------------------------------------------
Build Resume Files
--------------------------------------------------
*/

function buildHTML() {
  try {
    console.log("Generating resume.html...");

    execFileSync(
      "pandoc",
      [BUILD_MD, "-o", path.join(OUTPUT_DIR, "resume.html")],
      {
        stdio: "inherit",
      }
    );
  } catch {
    console.warn("⚠️ Pandoc not installed — skipping HTML build");
  }
}

function buildPDF() {
  try {
    console.log("Generating resume.pdf...");

    const pdfPath = path.join(OUTPUT_DIR, "resume.pdf");

    execFileSync(
      "pandoc",
      [
        BUILD_MD,
        "-o",
        pdfPath,
        "--pdf-engine=xelatex",
        // Tight résumé layout: narrow margins, 10pt, compact lists/sections.
        "-H",
        path.join(ROOT, "scripts", "resume-header.tex"),
        "-V",
        "fontsize=10pt",
        "-V",
        // XCharter, not Charter: it is the same typeface design and ships
        // with TeX Live on both macOS and Ubuntu, so a CI-built PDF is
        // identical to a locally built one. That is what makes the automatic
        // refresh safe — otherwise the two would overwrite each other forever.
        `mainfont=${process.env.RESUME_MAINFONT || "XCharter"}`,
      ],
      { stdio: "inherit" }
    );

    // Keep the downloadable résumé (served from /static) in sync with the build.
    const staticPdf = path.join(ROOT, "static", "resume.pdf");
    fs.copyFileSync(pdfPath, staticPdf);
    console.log("✅ Synced static/resume.pdf");
  } catch (error) {
    // Skipping is fine on a laptop without TeX. In CI it means the résumé
    // silently stopped building, which is how this went unnoticed — so fail
    // loudly there instead.
    if (process.env.CI) {
      console.error("❌ PDF build failed");
      throw error;
    }
    console.warn("⚠️ Pandoc/xelatex not installed — skipping PDF build");
  }
}

/*
--------------------------------------------------
Main
--------------------------------------------------
*/

function run() {
  console.log("🚀 Building resume pipeline...");

  ensureDirectories();

  const markdown = readResume();

  buildResumeData(markdown);

  // pandoc reads the composed copy, never the source
  fs.writeFileSync(BUILD_MD, withProjects(markdown));

  buildHTML();
  buildPDF();

  console.log("✨ Resume build complete");
}

run();
