// Bundles the icons the site actually uses, so no browser ever has to ask a
// third party for one.
//
// @iconify/svelte resolves an unknown icon name over the network — every
// visitor was hitting api.iconify.design, with api.unisvg.com as a fallback.
// That leaks the referrer, adds two hosts to the critical path, and makes the
// icons silently disappear for anyone whose blocker covers those domains
// (many block Iconify by default).
//
// Registering the icon data up front means the lookup always succeeds locally
// and the fetch never happens. Only the icons found in the source are
// included: the three collections together hold ~14,000, and the site uses
// about thirty.
//
// Run `npm run build-icons` after adding an icon. The generated file is
// committed, same as resumeData.ts, so a normal build needs no extra step.
import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "src");
const OUT = path.join(ROOT, "src/lib/generated/icons.ts");

/** `prefix:name`, the form @iconify/svelte takes in an `icon` prop. */
const ICON_RE = /["'`]([a-z0-9-]+):([a-z0-9-]+)["'`]/g;

function sourceFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return sourceFiles(full);
    return /\.(svelte|ts|js)$/.test(entry.name) ? [full] : [];
  });
}

// A collection is only loaded if the source actually names its prefix, so
// adding one is a matter of using it rather than editing a list here.
function loadCollection(prefix: string) {
  try {
    return JSON.parse(
      fs.readFileSync(
        path.join(ROOT, "node_modules", `@iconify-json/${prefix}/icons.json`),
        "utf8"
      )
    );
  } catch {
    return null;
  }
}

const found = new Map<string, Set<string>>();
for (const file of sourceFiles(SRC)) {
  if (file.includes("/generated/")) continue;
  const text = fs.readFileSync(file, "utf8");
  for (const [, prefix, name] of text.matchAll(ICON_RE)) {
    if (!found.has(prefix)) found.set(prefix, new Set());
    found.get(prefix)!.add(name);
  }
}

const entries: string[] = [];
const missing: string[] = [];
let scanned = 0;

for (const [prefix, names] of [...found].sort()) {
  const collection = loadCollection(prefix);
  // Most `word:word` matches are not icons at all — CSS values, URLs, times.
  // A prefix with no installed collection simply isn't one.
  if (!collection) continue;

  for (const name of [...names].sort()) {
    scanned += 1;
    // An alias points at another icon in the same collection; resolve it so
    // the registered name still renders.
    const resolved = collection.aliases?.[name]?.parent ?? name;
    const icon = collection.icons?.[resolved];
    if (!icon) {
      missing.push(`${prefix}:${name}`);
      continue;
    }
    entries.push(
      `  "${prefix}:${name}": ${JSON.stringify({
        body: icon.body,
        width: icon.width ?? collection.width ?? 16,
        height: icon.height ?? collection.height ?? 16,
      })},`
    );
  }
}

// A name that resolves to nothing used to fail silently — the icon just never
// appeared, because the network lookup 404'd in the browser. Failing the build
// instead turns a typo into something you find before it ships.
if (missing.length) {
  throw new Error(
    `buildIcons: not found in their collections: ${missing.join(", ")}`
  );
}

const file = `// Generated by \`npm run build-icons\` from the icon names used in src/.
// Do not edit.
import { addIcon } from "@iconify/svelte";

const icons: Record<string, { body: string; width: number; height: number }> = {
${entries.join("\n")}
};

// Registering before any <Icon> renders is what keeps the lookup local. This
// module is imported for its side effect by the root layout.
for (const [name, data] of Object.entries(icons)) {
  addIcon(name, data);
}

export const bundledIconNames = Object.keys(icons);
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, file);
console.log(
  `✅ ${entries.length} icons bundled (${scanned} names scanned) → ${path.relative(ROOT, OUT)}`
);
